# Generated by Django 5.2.17 on 2026-09-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True, help_text='OPIS Truckstop ID from fuel data')),
                ('name', models.CharField(help_text='Truckstop brand or business name', max_length=255)),
                ('address', models.CharField(help_text='Street address or highway junction', max_length=255)),
                ('city', models.CharField(db_index=True, help_text='City name', max_length=128)),
                ('state', models.CharField(db_index=True, help_text='US state two-letter postal abbreviation', max_length=10)),
                ('rack_id', models.IntegerField(blank=True, help_text='Rack identifier from fuel pricing feed', null=True)),
                ('retail_price', models.DecimalField(db_index=True, decimal_places=4, help_text='Retail diesel price in USD per gallon', max_digits=8)),
                ('latitude', models.FloatField(blank=True, db_index=True, help_text='WGS-84 latitude in decimal degrees', null=True)),
                ('longitude', models.FloatField(blank=True, db_index=True, help_text='WGS-84 longitude in decimal degrees', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fuel_stations',
                'ordering': ['state', 'city', 'retail_price'],
                'indexes': [models.Index(fields=['state', 'city'], name='idx_station_state_city'), models.Index(fields=['latitude', 'longitude'], name='idx_station_lat_lon'), models.Index(fields=['retail_price'], name='idx_station_price')],
            },
        ),
    ]
